=== liveart/liveartjs/schema/model/config/Social.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "https://liveart/config/Social.schema.json",
  "title": "Social",
  "description": "Social configuration",
  "type": "object",
  "version": "1.1.0",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Reference to JSON Schema of the supported version"
    },
    "instagramClientID": {
      "type": "string"
    },
    "facebookClientID": {
      "type": "string"
    },
    "flickrClientID": {
      "type": "string"
    },
    "googleClientID": {
      "type": "string"
    },
    "authorizedRedirectUrl": {
      "type": "string"
    }
  },
  "required": [],
  "additionalProperties": false
}

=== liveart/liveartjs/config/social.json
{
  "$schema": "../schema/model/config/Social.schema.json",
  "instagramClientID": "703ce71d4f614162891607d355fd428a",
  "facebookClientID": "281642648841375",
  "flickrClientID": "dfd7520d89c31ccd49585c695793ac9c",
  "googleClientID": "342176054623-gnef4h5hu2jut5cv2hi7iuhn3lsn7mpc.apps.googleusercontent.com",
  "authorizedRedirectUrl": "http://demo.liveartdesigner.com/LAJS100/services/static/socialRedirect.html"
}
