=== liveart/liveartjs/schema/model/service/design/DesignDataObject.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "https://liveart/service/design/DesignDataObject.schema.json",
  "title": "DesignDataObject",
  "type": "object",
  "version": "1.2",
  "properties": {
    "version": {
      "type": "string",
      "minLength": 1
    },
    "strict": {
      "type": "boolean"
    },
    "product": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "template": {
          "type": "string",
          "minLength": 1
        },
        "productColors": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "value": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "name",
              "value"
            ],
            "additionalProperties": false
          }
        },
        "color": {
          "type": "string",
          "minLength": 1
        },
        "colorName": {
          "type": "string",
          "minLength": 1
        },
        "size": {
          "type": "object",
          "properties": {
            "width": {
              "type": "number"
            },
            "height": {
              "type": "number"
            }
          },
          "required": [
            "width",
            "height"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "locations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "editableArea": {
            "type": "string"
          },
          "svg": {
            "type": "string"
          },
          "visible": {
            "type": "boolean",
            "default": true
          }
        },
        "required": [
          "name",
          "svg"
        ],
        "additionalProperties": false
      }
    },
    "fontsCSSUrl": {
      "type": "string",
      "minLength": 1
    },
    "quantities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "size": {
            "type": "string"
          },
          "quantity": {
            "type": "number"
          }
        },
        "required": [
          "quantity"
        ],
        "additionalProperties": false
      }
    },
    "prices": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          },
          "price": {
            "type": "string"
          },
          "isTotal": {
            "type": "boolean"
          }
        },
        "required": [
          "label",
          "price"
        ],
        "additionalProperties": false
      }
    },
    "namesNumbers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "numberText": {
            "type": "string"
          },
          "size": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "numberText",
          "size"
        ],
        "additionalProperties": false
      }
    },
    "notes": {
      "type": "string"
    },
    "design": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "shared",
            "saved",
            "ordered",
            "template",
            "design idea",
            "service"
          ]
        },
        "title": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "options": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "optionId": {
            "type": "string",
            "minLength": 1
          },
          "optionName": {
            "type": "string",
            "minLength": 1
          },
          "variationId": {
            "type": "string",
            "minLength": 1
          },
          "variationName": {
            "type": "string",
            "minLength": 1
          },
          "value": {
            "type": "boolean"
          }
        },
        "required": [
          "optionId",
          "optionName"
        ],
        "additionalProperties": false
      }
    },
    "guides": {
      "type": "object",
      "properties": {
        "horizontal": {
          "type": "array",
          "items": {
            "type": "number"
          }
        },
        "vertical": {
          "type": "array",
          "items": {
            "type": "number"
          }
        }
      },
      "required": [
        "horizontal",
        "vertical"
      ],
      "additionalProperties": false
    },
    "productId": {
      "type": "string",
      "minLength": 1
    },
    "quote": {
      "$ref": "../quote/GetQuoteRequest.schema.json"
    }
  },
  "required": [
    "locations",
    "design"
  ],
  "additionalProperties": false
}

=== liveart/liveartjs/files/template-standard-sign-yard-sign/design.json
{"product":{"id":"41_template","name":"Template Open House (Standard sign)","productColors":[{"id":".bcg[fill]","name":"Background","value":"#FFFFFF"}],"size":{"width":24,"height":18}},"locations":[{"name":"Front","svg":"<svg height=\"530\" version=\"1.1\" width=\"590\" xmlns=\"http:\/\/www.w3.org\/2000\/svg\" viewBox=\"0 0 590 442.497\" xmlns:xlink=\"http:\/\/www.w3.org\/1999\/xlink\"><defs><mask id=\"maskSjp01pjh514m\" xmlns=\"http:\/\/www.w3.org\/2000\/svg\"><g><rect x=\"-295\" y=\"-326.14756126914665\" width=\"1180\" height=\"1094.7921225382934\" fill=\"#808080\" style=\"\"><\/rect><rect id=\"la-product-mask_4424_\" width=\"590\" height=\"530\" transform=\"matrix(1,0,0,0.8349,0,0)\" fill=\"#ffffff\" style=\"\"><\/rect><\/g><\/mask><\/defs><desc>Created with Snap<\/desc><g class=\"la-layer la-bottom-layer\" xmlns=\"http:\/\/www.w3.org\/2000\/svg\"><g version=\"1.1\" id=\"obj-1543341558459-6224\" xmlns=\"http:\/\/www.w3.org\/2000\/svg\" x=\"0px\" y=\"0px\" width=\"590px\" height=\"530px\" viewBox=\"0 0 590 530\" enable-background=\"new 0 0 590 530\" xml:space=\"preserve\" la-config-colors=\"0\" transform=\"matrix(1,0,0,0.8349,0,0)\" la-type=\"svg\" la-service=\"s-background\" class=\"object notselectable la-rotatable la-lockable\" la-scale-range=\"1,5\" la-colorize=\"true\" preserveAspectRatio=\"xMidYMid\">\n\t<rect id=\"la_x7C_Background_x7C_bcg_70347_\" fill=\"#ffffff\" stroke=\"#000000\" stroke-miterlimit=\"10\" width=\"590\" height=\"530\" class=\"bcg\" style=\"\"><\/rect>\n\t\n<desc>Created with Snap<\/desc><defs><\/defs><\/g><\/g><g class=\"la-layer la-main-layer\" mask=\"url('#maskSjp01pjh514m')\" xmlns=\"http:\/\/www.w3.org\/2000\/svg\"><g version=\"1.1\" id=\"obj-1542897990530-5141\" xmlns=\"http:\/\/www.w3.org\/2000\/svg\" xmlns:xlink=\"http:\/\/www.w3.org\/1999\/xlink\" x=\"0px\" y=\"0px\" width=\"100px\" height=\"100px\" viewBox=\"0 0 100 100\" enable-background=\"new 0 0 100 100\" xml:space=\"preserve\" la-config-colors=\"0\" la-graphics-id=\"6s01\" fill=\"#9e9e9e\" style=\"\" transform=\"matrix(5.9059,0,0,1.7831,0,0)\" la-type=\"svg\" la-service=\"s-88051542897990530\" la-colorize=\"true\" class=\"object la-rotatable la-lockable required fixed-position\">\n<rect width=\"100\" height=\"100\"><\/rect>\n<desc>Created with Snap<\/desc><defs><\/defs><\/g><g la-text-data=\"%7B%22id%22%3A%22obj-1542898044123-4031%22%2C%22type%22%3A%22text%22%2C%22la-service%22%3A%22s-19611542898044123%22%2C%22version%22%3A1%2C%22fillCanvas%22%3Afalse%2C%22invisibleTracker%22%3Afalse%2C%22restrictions%22%3A%7B%22scaleRange%22%3Anull%2C%22selectable%22%3Atrue%2C%22userFixed%22%3Afalse%2C%22required%22%3Atrue%2C%22fixedPosition%22%3Afalse%2C%22constrainedArea%22%3A%7B%22x%22%3A12.983126098050832%2C%22y%22%3A3.8112026276612374%2C%22w%22%3A564.0338388196883%2C%22h%22%3A101.7774612892339%7D%2C%22rotatable%22%3Atrue%2C%22lockable%22%3Atrue%7D%2C%22fill%22%3A%22%23D32F2F%22%2C%22font-family%22%3A%22ChunkFive%22%2C%22font-size%22%3A32%2C%22font-style%22%3A%22normal%22%2C%22font-weight%22%3A%22normal%22%2C%22letter-spacing%22%3A%220%22%2C%22line-leading%22%3A1.2%2C%22stroke%22%3A%22%23FFFFFF%22%2C%22stroke-width%22%3A%221%22%2C%22text%22%3A%22Text%20Line%201%22%2C%22textPrompt%22%3A%22New%20Text%22%2C%22text-align%22%3A%22center%22%2C%22text-type%22%3A%22%22%2C%22textEffect%22%3A%22none%22%2C%22textEffectValue%22%3A%220%22%2C%22vector-type%22%3A%22vector%22%2C%22isNameObject%22%3Afalse%2C%22isNumberObject%22%3Afalse%7D\" vector-type=\"vector\" class=\"la-rotatable la-lockable object required\" transform=\"matrix(3.2873,0,0,3.1628,11.9969,61.9779)\" id=\"obj-1542898044123-4031\" la-type=\"text\" la-service=\"s-19611542898044123\" la-area-constrained=\"12.983126098050832 3.8112026276612374 564.0338388196883 101.7774612892339\" xmlns:xlink=\"http:\/\/www.w3.org\/1999\/xlink\"><g><path d=\"M0.8,-4.711111C0.8,-4.711111,0.8,-13.066667,0.8,-13.066667C0.8,-13.066667,22.311111,-13.066667,22.311111,-13.066667C22.311111,-13.066667,22.311111,-4.711111,22.311111,-4.711111C22.311111,-4.711111,17.6,-4.711111,17.6,-4.711111C17.6,-4.711111,17.6,-8.8,17.6,-8.8C17.6,-8.8,14.933333,-8.8,14.933333,-8.8C14.933333,-8.8,14.933333,5.066667,14.933333,5.066667C14.933333,5.066667,17.6,5.066667,17.6,5.066667C17.6,5.066667,17.6,9.333333,17.6,9.333333C17.6,9.333333,5.688889,9.333333,5.688889,9.333333C5.688889,9.333333,5.688889,5.066667,5.688889,5.066667C5.688889,5.066667,8.266667,5.066667,8.266667,5.066667C8.266667,5.066667,8.266667,-8.8,8.266667,-8.8C8.266667,-8.8,5.511111,-8.8,5.511111,-8.8C5.511111,-8.8,5.511111,-4.711111,5.511111,-4.711111C5.511111,-4.711111,0.8,-4.711111,0.8,-4.711111C0.8,-4.711111,0.8,-4.711111,0.8,-4.711111M39.644444,7.111111C34.311111,12.177778,22.933333,10.4,22.933333,1.244444C22.933333,-3.822222,26.577778,-7.111111,31.555556,-7.111111C37.244444,-7.111111,40.888889,-2.844444,39.2,2.933333C39.2,2.933333,29.155556,2.933333,29.155556,2.933333C29.422222,6.4,34.844444,5.955556,36.888889,4C36.888889,4,39.644444,7.111111,39.644444,7.111111M34.044444,-0.266667C34.577778,-2.844444,31.022222,-3.466667,29.866667,-1.955556C29.511111,-1.422222,29.244444,-0.888889,29.244444,-0.266667C29.244444,-0.266667,34.044444,-0.266667,34.044444,-0.266667C34.044444,-0.266667,34.044444,-0.266667,34.044444,-0.266667M40.711111,9.333333C40.711111,9.333333,40.711111,5.333333,40.711111,5.333333C40.711111,5.333333,42.844444,5.333333,42.844444,5.333333C42.844444,5.333333,46.133333,1.688889,46.133333,1.688889C46.133333,1.688889,42.133333,-2.666667,42.133333,-2.666667C42.133333,-2.666667,40.711111,-2.666667,40.711111,-2.666667C40.711111,-2.666667,40.711111,-6.666667,40.711111,-6.666667C40.711111,-6.666667,51.111111,-6.666667,51.111111,-6.666667C51.111111,-6.666667,51.111111,-2.666667,51.111111,-2.666667C51.111111,-2.666667,49.6,-2.666667,49.6,-2.666667C49.6,-2.666667,51.822222,-0.266667,51.822222,-0.266667C51.822222,-0.266667,54.222222,-2.666667,54.222222,-2.666667C54.222222,-2.666667,52.088889,-2.666667,52.088889,-2.666667C52.088889,-2.666667,52.088889,-6.666667,52.088889,-6.666667C52.088889,-6.666667,60.266667,-6.666667,60.266667,-6.666667C60.266667,-6.666667,60.266667,-2.666667,60.266667,-2.666667C60.266667,-2.666667,58.133333,-2.666667,58.133333,-2.666667C58.133333,-2.666667,54.755556,0.711111,54.755556,0.711111C54.755556,0.711111,58.755556,5.333333,58.755556,5.333333C58.755556,5.333333,60.266667,5.333333,60.266667,5.333333C60.266667,5.333333,60.266667,9.333333,60.266667,9.333333C60.266667,9.333333,50.044444,9.333333,50.044444,9.333333C50.044444,9.333333,50.044444,5.333333,50.044444,5.333333C50.044444,5.333333,51.555556,5.333333,51.555556,5.333333C51.555556,5.333333,49.155556,2.755556,49.155556,2.755556C49.155556,2.755556,46.844444,5.333333,46.844444,5.333333C46.844444,5.333333,48.888889,5.333333,48.888889,5.333333C48.888889,5.333333,48.888889,9.333333,48.888889,9.333333C48.888889,9.333333,40.711111,9.333333,40.711111,9.333333C40.711111,9.333333,40.711111,9.333333,40.711111,9.333333M68.088889,9.955556C61.777778,10.4,63.2,3.377778,63.022222,-2.488889C63.022222,-2.488889,61.244444,-2.488889,61.244444,-2.488889C61.244444,-2.488889,61.244444,-6.666667,61.244444,-6.666667C61.244444,-6.666667,63.022222,-6.666667,63.022222,-6.666667C63.022222,-6.666667,63.022222,-9.6,63.022222,-9.6C63.022222,-9.6,68.888889,-11.466667,68.888889,-11.466667C68.888889,-11.466667,68.888889,-6.666667,68.888889,-6.666667C68.888889,-6.666667,71.911111,-6.666667,71.911111,-6.666667C71.911111,-6.666667,71.911111,-2.488889,71.911111,-2.488889C71.911111,-2.488889,68.888889,-2.488889,68.888889,-2.488889C68.888889,-2.488889,68.977778,5.066667,68.977778,5.066667C69.422222,6.133333,70.666667,5.777778,71.911111,5.244444C71.911111,5.244444,71.911111,9.333333,71.911111,9.333333C71.111111,9.6,68.977778,9.866667,68.088889,9.955556C68.088889,9.955556,68.088889,9.955556,68.088889,9.955556M81.155556,9.333333C81.155556,9.333333,81.155556,5.066667,81.155556,5.066667C81.155556,5.066667,82.933333,5.066667,82.933333,5.066667C82.933333,5.066667,82.933333,-8.8,82.933333,-8.8C82.933333,-8.8,81.155556,-8.8,81.155556,-8.8C81.155556,-8.8,81.155556,-13.066667,81.155556,-13.066667C81.155556,-13.066667,91.288889,-13.066667,91.288889,-13.066667C91.288889,-13.066667,91.288889,-8.8,91.288889,-8.8C91.288889,-8.8,89.6,-8.8,89.6,-8.8C89.6,-8.8,89.6,5.066667,89.6,5.066667C89.6,5.066667,93.688889,5.066667,93.688889,5.066667C93.688889,5.066667,93.688889,0.977778,93.688889,0.977778C93.688889,0.977778,99.111111,0.977778,99.111111,0.977778C99.111111,0.977778,99.111111,9.333333,99.111111,9.333333C99.111111,9.333333,81.155556,9.333333,81.155556,9.333333C81.155556,9.333333,81.155556,9.333333,81.155556,9.333333M100.622222,9.333333C100.622222,9.333333,100.622222,5.155556,100.622222,5.155556C100.622222,5.155556,101.955556,5.155556,101.955556,5.155556C101.955556,5.155556,101.955556,-2.488889,101.955556,-2.488889C101.955556,-2.488889,100.622222,-2.488889,100.622222,-2.488889C100.622222,-2.488889,100.622222,-6.666667,100.622222,-6.666667C100.622222,-6.666667,108,-6.666667,108,-6.666667C108,-6.666667,108,5.155556,108,5.155556C108,5.155556,109.6,5.155556,109.6,5.155556C109.6,5.155556,109.6,9.333333,109.6,9.333333C109.6,9.333333,100.622222,9.333333,100.622222,9.333333C100.622222,9.333333,100.622222,9.333333,100.622222,9.333333M104.977778,-8.088889C103.2,-8.088889,101.422222,-9.777778,101.511111,-11.377778C101.511111,-12.977778,103.022222,-14.577778,104.977778,-14.577778C106.933333,-14.577778,108.533333,-13.066667,108.533333,-11.377778C108.533333,-9.511111,107.022222,-8.088889,104.977778,-8.088889C104.977778,-8.088889,104.977778,-8.088889,104.977778,-8.088889M122.488889,0.622222C122.577778,-0.977778,122.222222,-2.4,120.711111,-2.4C117.955556,-2.488889,118.755556,2.311111,118.666667,5.155556C118.666667,5.155556,120.977778,5.155556,120.977778,5.155556C120.977778,5.155556,120.977778,9.333333,120.977778,9.333333C120.977778,9.333333,111.111111,9.333333,111.111111,9.333333C111.111111,9.333333,111.111111,5.155556,111.111111,5.155556C111.111111,5.155556,112
